export const importedContacts = [
  {
    "company": "Berger Installationen",
    "person": "",
    "title": "Elektriker",
    "phone": "032 652 54 41 / 079 631 37 40",
    "email": "",
    "website": "",
    "address": "Krähenbergstrasse 3\n2543 Lengnau\nCH",
    "labels": "Grenchen ::: * myContacts",
    "notes": "Werder von Grenchen hat die Arbeiten abgewiesen"
  },
  {
    "company": "AutoWidmer AG",
    "person": "",
    "title": "",
    "phone": "041 495 34 00",
    "email": "",
    "website": "",
    "address": "Rüediswilerstrasse 17\n6017 Ruswil\nCH",
    "labels": "Meinrad Privat ::: Eich ::: * myContacts",
    "notes": "Wohnmobil"
  },
  {
    "company": "Data Quest AG",
    "person": "",
    "title": "",
    "phone": "0900 576 292",
    "email": "",
    "website": "",
    "address": "Pilatusstrasse 18\n6003 Luzern\nCH",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Selmoni-Burger AG (Elektriker)",
    "person": "Adrian Dobler",
    "title": "Projektleiter",
    "phone": "079 472 9583 / 061 766 99 61 / 061 766 99 66",
    "email": "adrian.dobler@selmoni-burger.ch / adrian.dobler@selmoni-burger.ch",
    "website": "https://www.selmoni-burger.ch/Home/ / https://www.selmoni-burger.ch/Home/",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": "Zentral: Frau Müller\nGeschäftsführer: Herr Flury"
  },
  {
    "company": "Adrian Roth",
    "person": "Adrian Roth",
    "title": "",
    "phone": "",
    "email": "aj.roth@bluewin.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Kundmatt",
    "person": "Adrian Spies",
    "title": "",
    "phone": "079 270 28 72",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: * myContacts",
    "notes": "Mitmieterin Michelle Henz"
  },
  {
    "company": "Steiner Energietechnik",
    "person": "Alessia Sanner-Steiner",
    "title": "",
    "phone": "061 773 92 10",
    "email": "a.sanner@sk-energie.ch",
    "website": "https://www.sk-energie.ch/",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Alexander Borer",
    "person": "Alexander Borer",
    "title": "Sanitär, Heizung",
    "phone": "061 771 09 89 / 079 302 58 38",
    "email": "alexander.borer@gmx.ch / alexander.borer@bluewin.ch",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": "Kleinlützel:\n- Bodenheizung Parterre\n- Sanitär"
  },
  {
    "company": "Mieter Hilterfingen - 2. Stock",
    "person": "Amylin Olesco",
    "title": "",
    "phone": "076 334 11 20 / 076 579 31 50",
    "email": "amy.olesco@mail.ch / amy.olesco@mail.ch",
    "website": "",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": "Neu: Amylyn Ausan"
  },
  {
    "company": "B & M Fenster und Montagen GmbH",
    "person": "Andrea Burger-Dietrich",
    "title": "",
    "phone": "079 693 84 17 / 078 853 26 20 / 079 350 63 46",
    "email": "info@bm-storen.ch",
    "website": "https://www.bm-fenster.ch/",
    "address": "Zollbrück\nCH",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Schilt Elektro AG",
    "person": "Andrea Schaad",
    "title": "",
    "phone": "032 654 10 80",
    "email": "andrea.schaad@schiltelektro.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Schürch-Egli AG",
    "person": "Andreas Eiholzer",
    "title": "",
    "phone": "079 714 23 31 / 041 462 50 00",
    "email": "a.eiholzer@schuerch-egli.ch",
    "website": "",
    "address": "Allmend 45\n6204 Sempach\nCH",
    "labels": "* myContacts",
    "notes": "PV Anlage Eich\nDach Fassade Solar"
  },
  {
    "company": "Lumenpraxis",
    "person": "Andreas Kurmann",
    "title": "",
    "phone": "041 460 33 33",
    "email": "lumenpraxis@hin.ch",
    "website": "www.lumenpraxis.ch",
    "address": "Grenzstrasse 5b\n6214 Schenkon\nCH",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Loosli-Holzbau AG",
    "person": "Andreas Loosli",
    "title": "",
    "phone": "033 251 19 09 / 079 273 81 85",
    "email": "info@loosliholzbau.ch / info@loosliholzbau.ch ::: loosli.andreas@bluewin.ch",
    "website": "https://loosliholzbau.ch/",
    "address": "",
    "labels": "Aeschlen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mosimann Schreinerei AG",
    "person": "Andreas Mosimann",
    "title": "Geschäftsführer",
    "phone": "034 402 17 50",
    "email": "anmo@mosimann-schreinerei.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Grenchen_Parterre",
    "person": "Anita Kummer",
    "title": "",
    "phone": "079 583 27 89",
    "email": "anita2kummer@gmail.com",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Alpha Control",
    "person": "Anna Hofstetter",
    "title": "",
    "phone": "032 511 11 32",
    "email": "hofstetter@alphagmbh.swiss",
    "website": "",
    "address": "Selzach\nCH",
    "labels": "Grenchen ::: * myContacts",
    "notes": "Kontrolleur - Thoms Ast"
  },
  {
    "company": "SWG",
    "person": "Antonio Bögli",
    "title": "Projektleiter",
    "phone": "032 654 66 31",
    "email": "antonio.boegli@swg.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Langnau",
    "person": "Barbara Ighodaro",
    "title": "",
    "phone": "079 624 95 43 / 034 402 64 73",
    "email": "b.ighodaro@bluewin.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": "Mitmieter Rene Heer 079 699 31 91"
  },
  {
    "company": "Steueramt Solothurn - Veranlagungsbehörde",
    "person": "Barbara Müller",
    "title": "",
    "phone": "061 704 70 61",
    "email": "barbara.mueller@fd.so.ch",
    "website": "steueramt.so.ch",
    "address": "Amthausstrasse 15\n4143 Dornach\nCH",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "V-Zug",
    "person": "Baschung Cornelia",
    "title": "Sachbearbeiterin",
    "phone": "058 767 80 07",
    "email": "Cornelia.Baschung@vzug.com",
    "website": "",
    "address": "Industriestrasse 66\n6302 Zug\nCH",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "BE-Login",
    "person": "BE-Login",
    "title": "",
    "phone": "031 636 99 99 ::: 031 636 99 99",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Aeschlen ::: Hilterfingen ::: Langnau ::: * myContacts",
    "notes": "Das ist der Support für die BE-Login"
  },
  {
    "company": "Christ Maler",
    "person": "Beat Christ",
    "title": "",
    "phone": "077 520 82 15",
    "email": "mattiasamona@gmail.com",
    "website": "",
    "address": "Kleinlützel\nCH",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Oppliger Elektro AG",
    "person": "Beat Christen",
    "title": "",
    "phone": "033 553 05 05 / 033 553 05 05",
    "email": "beat.christen@oppliger-elektro.ch / beat.christen@oppliger-elektro.ch",
    "website": "https://www.oppliger-elektro.ch/ / https://www.oppliger-elektro.ch/",
    "address": "",
    "labels": "Aeschlen ::: Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Beat Schaller",
    "person": "Beat Schaller",
    "title": "",
    "phone": "033 227 27 27",
    "email": "beat.schaller@schmutzthun.ch",
    "website": "www.schmutzthun.ch",
    "address": "Mittlere Str. 70\nThun 3600\nCH",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": "Rohrreinigung & Kranarbeiten\n"
  },
  {
    "company": "ITS Kanal",
    "person": "Benjamin Lehmann",
    "title": "",
    "phone": "079 902 00 18",
    "email": "Benjamin.Lehmann@itskanal.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Raiffaisenbank Laufen-Thierstein",
    "person": "Berkan Yüzüak",
    "title": "",
    "phone": "",
    "email": "b.yuezueak@raiffeisen.ch / b.yuezueak@raiffeisen.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": "Vertretung von Hr. Ritter der seit dem 23-09-2025 im Vaterschaftsurlaub ist."
  },
  {
    "company": "Mobiliar",
    "person": "Bernard Freiburghaus",
    "title": "",
    "phone": "041 926 76 59",
    "email": "bernard.freiburghaus@mobi.ch",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Elektro Liechti AG",
    "person": "Bernhard Fankhauser",
    "title": "",
    "phone": "034 408 34 34",
    "email": "b.fankhauser@elektro-liechti.ch",
    "website": "www.elektro-liechti.ch",
    "address": "Napfstrasse 49\nLangnau 3550\nCH",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Thuner Bau AG",
    "person": "Bernhard Hofer",
    "title": "",
    "phone": "034 495 59 81 / 079 343 12 69",
    "email": "info@thunerbauag.ch / info@thunerbauag.ch ::: bernhard.hofer@thunerbauag.ch",
    "website": "https://thunerbauag.ch/",
    "address": "3555\nTrubschachen\nCH",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Tschümperlin Lötscher Schwarz AG",
    "person": "Birchler Karin",
    "title": "Assistentin",
    "phone": "041 419 30 30",
    "email": "K.Birchler@tls-partner.ch",
    "website": "",
    "address": "Löwenstrasse 3\n6000 Luzern  6\nCH",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Bruno Hügli AG",
    "person": "Bruno Hügli",
    "title": "",
    "phone": "061 781 19 70",
    "email": "info@huegli-ag.ch",
    "website": "https://www.huegli-ag.ch/",
    "address": "Grienackerweg 7\n4226 Breitenbach\nCH",
    "labels": "Traube ::: * myContacts",
    "notes": "Flachdach, Fassaden, Spengler"
  },
  {
    "company": "Bauknecht",
    "person": "Bruno Migliaretti",
    "title": "",
    "phone": "",
    "email": "bruno.migliaretti@europeanappliances.com",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Buerobedarf-Estermann",
    "person": "Buerobedarf-Estermann",
    "title": "",
    "phone": "041 920 12 12",
    "email": "info@buerobedarf-estermann.ch",
    "website": "https://www.buerobedarf-estermann.ch/",
    "address": "Stadthof\nSursee\nCH",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Apotheke Surseepark",
    "person": "Celine Hüsler",
    "title": "",
    "phone": "041 921 78 21",
    "email": "surseepark@ovan.ch",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Eigentuemerversammlung Huneggweg 2",
    "person": "Christian Ammann",
    "title": "",
    "phone": "033 243 31 69",
    "email": "ammann-ch@bluewin.ch",
    "website": "",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Christof Marti",
    "person": "Christof Marti",
    "title": "",
    "phone": "(604) 440-2864",
    "email": "",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "PW\nModelNu..yr built"
  },
  {
    "company": "Fritz Amstutz AG",
    "person": "Christoph Harnisch",
    "title": "",
    "phone": "033 222 36 52 / 079 656 82 27",
    "email": "christoph.harnisch@amstutz-maler.ch",
    "website": "www.amstutz-maler.ch",
    "address": "",
    "labels": "Aeschlen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Kühni Sanitär",
    "person": "Christoph Perucchi",
    "title": "",
    "phone": "079 460 09 62",
    "email": "chp@kuehniteam.ch",
    "website": "",
    "address": "Langnau\nCH",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "CKW",
    "person": "CKW",
    "title": "",
    "phone": "0800 887 766",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Fr. Gowsaliga Yogeswaran (Kundendienst/Chat +Tel vom 2025-03-21: 041 249 69 00"
  },
  {
    "company": "Mieter Aeschlen",
    "person": "Claudio Nigg",
    "title": "",
    "phone": "079 768 61 02",
    "email": "crnigg@gmail.com",
    "website": "",
    "address": "",
    "labels": "Aeschlen ::: * myContacts",
    "notes": "Mitmieter: Carina Nigg (früher Mnich)"
  },
  {
    "company": "MIKO",
    "person": "Daniel Brunner",
    "title": "",
    "phone": "",
    "email": "daniel.brunner@mikoimmobilien.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "St. Anna Klinik",
    "person": "Daniel Erni",
    "title": "Arzt für Angiologie und Innere Medizin",
    "phone": "041 208 48 55",
    "email": "angiologie-luzern@hin.ch",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Ludwig Meier & Söhne AG",
    "person": "Daniel Meier",
    "title": "Sanitär",
    "phone": "061 771 90 00 ::: +41796996606",
    "email": "info@LMUS.ch",
    "website": "www.lmus.ch",
    "address": "Kleinlützel\nCH",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Schreinerei Schwarz",
    "person": "Daniel Moning",
    "title": "Projektleiter Fenster",
    "phone": "079 543 54 36",
    "email": "d.moning@schreinereischwarz.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Hilterfingen_Parterre",
    "person": "David Weixelbaumer",
    "title": "",
    "phone": "079 177 26 02 ::: +41791772602",
    "email": "david.weixelbaumer@icloud.com",
    "website": "",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mobiliar",
    "person": "Domenico Gervasio",
    "title": "",
    "phone": "",
    "email": "domenico.gervasio@mobiliar.ch / domenico.gervasio@mobi.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Restaurant Kleinlützel",
    "person": "Don Peppe",
    "title": "",
    "phone": "061 771 91 69",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Steuern Sempach/Eich",
    "person": "Doris Williman",
    "title": "",
    "phone": "041 462 52 34",
    "email": "d.willimann@sempach.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Zahnarzt Eich",
    "person": "Dres. Mühlebach & Reinert",
    "title": "",
    "phone": "041 460 02 02",
    "email": "info@zape.ch",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": ""
  },
  {
    "company": "SiNa",
    "person": "Eidgenössisches Starkstrom Inspektoriat - ESTI",
    "title": "",
    "phone": "",
    "email": "info@esti.admin.ch",
    "website": "https://verzeichnisse.esti.ch/de/aikb.htm",
    "address": "",
    "labels": "* myContacts",
    "notes": "SiNa\n"
  },
  {
    "company": "Gemeindeverwaltung Kleinlützel",
    "person": "Einwohnergemeinde Kleinlützel",
    "title": "",
    "phone": "061 775 90 00",
    "email": "gemeinde@kleinluetzel.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": "Am Schalter:  Fr. Qendresa Salihi"
  },
  {
    "company": "Elektro Burri AG",
    "person": "Elektro Burri AG",
    "title": "",
    "phone": "041 467 15 20",
    "email": "",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Tschümperlin Lötscher Schwarz AG",
    "person": "Elias Mattmann-Fries",
    "title": "Rechtsanwalt und Notar",
    "phone": "041 419 30 30",
    "email": "e.mattmann@tls-partner.ch",
    "website": "www.tls-partner.ch",
    "address": "Löwenstrasse 3\n6004 Luzern\nCH",
    "labels": "* myContacts",
    "notes": "Hat auch eine Kanzlei in Sursee\n\nRaphi Vonaesch Kennt Elias Mattman.\nNiederlassung in Sursee & Luzern"
  },
  {
    "company": "Bauknecht",
    "person": "Elio Ianello",
    "title": "Verkauf",
    "phone": "",
    "email": "elio.jannello@europeanappliances.com",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Hilterfingen_1_Stock",
    "person": "Eliza Marat",
    "title": "",
    "phone": "079 516 45 66",
    "email": "elizamarat@windowslive.com",
    "website": "",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Traube",
    "person": "Erich Schmid",
    "title": "",
    "phone": "076 533 27 56",
    "email": "schmiric2@gmail.com",
    "website": "",
    "address": "Wasserstrasse 23\n4056 Basel\nCH",
    "labels": "Traube ::: * myContacts",
    "notes": "Lagerraum: Auf der rechten Seite der Traube"
  },
  {
    "company": "Röösli Gartenbau GmbH",
    "person": "Fabian Röösli",
    "title": "",
    "phone": "078 707 10 51",
    "email": "roeoesli.garten@bluewin.ch",
    "website": "www.röösli-garten.ch",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Hasler + Reinle AG",
    "person": "Fabio Jeker",
    "title": "",
    "phone": "079 520 30 32 / 061 7652060",
    "email": "f.jeker@hasler-reinle.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Kaminfeger Felix Weber",
    "person": "Felix  Weber",
    "title": "",
    "phone": "032 645 35 47",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Netzwerk Grenchen",
    "person": "Fernando Belardi",
    "title": "",
    "phone": "765803624",
    "email": "fernando.belardi@netzwerk-grenchen.ch",
    "website": "https://netzwerk-grenchen.ch/",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Feuerungskontrolle Kanton Bern",
    "person": "",
    "title": "",
    "phone": "031 636 70 01",
    "email": "feuerungskontrolle.aue@be.ch / feuerungskontrolle@be.ch ::: feuerungskontrolle.aue@be.ch",
    "website": "https://www.weu.be.ch/de/start/themen/umwelt/luft-laerm-strahlung/luft/feuerungen/feuerungskontrolle.html",
    "address": "",
    "labels": "Aeschlen ::: Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Gemeinderverwaltung Hilterfingen",
    "person": "Finanzverwaltung Hilterfingen",
    "title": "",
    "phone": "033 244 60 70",
    "email": "debitoren@hilterfingen.ch / finanzverwaltung@hilterfingen.ch",
    "website": "",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Fischer Heizung",
    "person": "Fischer Heizung",
    "title": "",
    "phone": "041 921 11 08",
    "email": "info@heizprofi.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Empfohlen von Stierli Sanitär in Sursee\nFür Heizkörper, z.b. Danfoss Ventile"
  },
  {
    "company": "EM Electrocontrol AG",
    "person": "Flavio Pizzurro",
    "title": "",
    "phone": "0800 99 99 66",
    "email": "flavio.pizzurro@electrocontrol.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "SiNa Kanton Bern"
  },
  {
    "company": "Mieter Hilterfingen_2_Stock",
    "person": "Florante Olesco",
    "title": "",
    "phone": "076 392 72 16",
    "email": "f.olesco@gmx.ch / jun.olempo@gmx.net ::: f.olesco@gmx.ch / f.olesco@gmx.ch",
    "website": "",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": "Mitmieterin Amylyn \namy.olesco@mail.ch\nFlorante - Telefon alt:0765793150 (an Amylin zurückgegeben)"
  },
  {
    "company": "4B - Fenster",
    "person": "Fr. Bashotaj",
    "title": "",
    "phone": "0848 800 405",
    "email": "service@4-b.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Elektro Nottwil AG",
    "person": "Fr. Bücheli-Felber",
    "title": "",
    "phone": "041 939 30 30 / 041 939 30 30",
    "email": "info@elektro-nottwil.ch / info@elektro-nottwil.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Jürg Kühni AG",
    "person": "Fr. Dahinden",
    "title": "",
    "phone": "344091114",
    "email": "buchhaltung@kuehniteam.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Elektro Liechti AG",
    "person": "Fr. Eberhart",
    "title": "",
    "phone": "034 408 34 34",
    "email": "info@elektro-liechti.ch / info@elektro-liechti.ch",
    "website": "https://elektro-liechti.ch/",
    "address": "Langnau\nCH",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Schilt Elektro AG",
    "person": "Fr. Flury",
    "title": "",
    "phone": "032 654 10 80",
    "email": "info@schiltelektro.ch / info@schiltelektro.ch / laden@schiltelektro.ch",
    "website": "https://www.schiltelektro.ch/",
    "address": "Leuzigenstrasse 22\n2540 Grenchen\nCH",
    "labels": "Grenchen ::: * myContacts",
    "notes": "Hat in der Hauptwohnung den Anschluss Oven geflickt als die Steuerungsbox der Heizpaneele in Flammen aufging.\n\nReferenzen:\nhttps://www.local.ch/de/q/grenchen/elektriker\n\nBüro: Fr. Flury\nFinanzen: Fr. Schaad\nInstallateur: Hr. Zuberbühler\nPM: Hr. Marti\n"
  },
  {
    "company": "Gebäudeversicherung SO",
    "person": "Fr. Lutz",
    "title": "",
    "phone": "032 627 97 20 ::: 032 627 97 20",
    "email": "versicherung@sgvso.ch / versicherung@sgvso.ch",
    "website": "https://www.sgvso.ch/kontakt/ ::: https://www.sgvso.ch/kontakt/",
    "address": "",
    "labels": "Versicherung ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Wasner Tank Revisioin",
    "person": "Fr. Wälti",
    "title": "",
    "phone": "+41 (0) 33 345 75 50 / 033 345 75 50",
    "email": "info@wasnerag.ch / info@wasnerag.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Steiner-Köng Energietechnik AG",
    "person": "Franceso Pangallo - Installateur",
    "title": "",
    "phone": "079 344 31 49",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Gebäudeversicherung  SO",
    "person": "Frau Bähler",
    "title": "",
    "phone": "032 627 97 20 ::: 032 627 97 20",
    "email": "finanzen@sgvso.ch / finanzen@sgvso.ch",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Primeo Energie",
    "person": "Frau Marktwalder",
    "title": "",
    "phone": "061 415 41 50",
    "email": "service@primeo-energie.ch",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": "Strom\n- Traube: 2 Zaehler (allgemeine fuer NK) und Sall (fuer MM)\n- Kundmatt: Laeuft ueber Mieter"
  },
  {
    "company": "Fürst Kaminfeger",
    "person": "Fürst Kaminfeger",
    "title": "",
    "phone": "061 761 6565",
    "email": "termin@drschwarzpeter.ch",
    "website": "https://www.drschwarzpeter.ch/",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Rotkreuz",
    "person": "Gabi Scherrer",
    "title": "",
    "phone": "079 126 60 79",
    "email": "",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Gall Entsorgung Eich",
    "person": "Gall Entsorgung Eich",
    "title": "",
    "phone": "",
    "email": "debitoren@gall-lu.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "4B",
    "person": "Galliker Julia",
    "title": "",
    "phone": "",
    "email": "julia.galliker@4-b.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Geberit",
    "person": "Geberit Serviceanfrage",
    "title": "",
    "phone": "0848 882 982",
    "email": "service.ch@geberit.com",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Grüter Hans AG",
    "person": "Geberit Vertreter",
    "title": "",
    "phone": "041 925 81 41",
    "email": "info@grueterag.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Gemeinde Langnau",
    "person": "Gemeindeverwaltung Langnau",
    "title": "",
    "phone": "034 409 31 11",
    "email": "finanzverwaltung@langnau-ie.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": "Bauabteiling - Fr. Schneider\nLeiter Tiefbauamt - Hr. Murer"
  },
  {
    "company": "Gemeindeverwaltung Sigriswil",
    "person": "",
    "title": "033 252 90 20",
    "phone": "",
    "email": "gemeindeverwaltung@sigriswil.ch",
    "website": "",
    "address": "",
    "labels": "Aeschlen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Estermann AG",
    "person": "Gina Estermann",
    "title": "",
    "phone": "",
    "email": "g.estermann@gt-e.ch",
    "website": "https://www.gt-e.ch/unternehmen",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Grundbuchamt Bern (Oberland)",
    "person": "Grundbuchamt Bern (Oberland)",
    "title": "",
    "phone": "031 636 24 50",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Aeschlen ::: Hilterfingen ::: Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Grundbuchamt Grenchen",
    "person": "Grundbuchamt Grenchen",
    "title": "",
    "phone": "032 654 55 10",
    "email": "gb.gr@fd.so.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Grundbuchamt Luzern",
    "person": "Grundbuchamt Luzern",
    "title": "",
    "phone": "041 318 12 00",
    "email": "",
    "website": "https://grundbuch.lu.ch/",
    "address": "",
    "labels": "Sempach ::: Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Grundbuchamt Thierstein",
    "person": "Grundbuchamt Thierstein",
    "title": "",
    "phone": "061 785 77 77",
    "email": "gb.th@fd.so.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Burri-Bodenbeläge",
    "person": "Guido Burri",
    "title": "",
    "phone": "079 745 40 71",
    "email": "guido@burri-bodenbelaege.ch",
    "website": "",
    "address": "Guetischwand 1\nRuswil 6017\nCH",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Sozialamt Thierstein",
    "person": "Gümrük",
    "title": "",
    "phone": "061 785 90 90",
    "email": "n.guemruek@zsth.ch",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Uroviva",
    "person": "Hannes Merker",
    "title": "Dr. med.",
    "phone": "062 794 01 50",
    "email": "julian.cornelius@uroviva.ch",
    "website": "",
    "address": "Bernstrasse 86\nRothrist 4852\nCH",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": "MPA Frau Hodel\nFrüher: Dr. Julius Cornelius"
  },
  {
    "company": "Mega Ohm",
    "person": "Heinz Müller",
    "title": "",
    "phone": "034 445 10 10 / 079 788 86 28",
    "email": "heinz.mueller@megaohm.ch / heinz.mueller@megaohm.ch :::  info@megaohm.ch",
    "website": "https://www.megaohm.ch/",
    "address": "Bernstrasse 3 - 5\n3421 Lyssach\nCH",
    "labels": "Aeschlen ::: Langnau ::: * myContacts",
    "notes": "Elektro - SiNa\nHr. Müller wohnt in Langnau"
  },
  {
    "company": "Messerli Bauteam",
    "person": "Heinz Ryf",
    "title": "",
    "phone": "033 222 15 44",
    "email": "hienz.ryf@messerli-bauteam.ch / heinz.ryf@messerli-bauteam.ch",
    "website": "",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "HEV Kanton Bern",
    "person": "HEV Kanton Bern",
    "title": "",
    "phone": "031 388 58 50",
    "email": "",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "HEV Langnau und Umgebung",
    "person": "HEV Langnau und Umgebung",
    "title": "",
    "phone": "034 408 00 40",
    "email": "",
    "website": "https://www.hev-langnau.ch/",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": "Empfang: Fr. Jackob\nRechtsberaterin: Fr. Althaus"
  },
  {
    "company": "HEV Luzern",
    "person": "HEV Luzern",
    "title": "",
    "phone": "041 211 12 13",
    "email": "info@hev-luzern.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "Mitglieder Nr:505911/070"
  },
  {
    "company": "HEV Schweiz Rechtshilfe - kostenpflichtig",
    "person": "HEV Schweiz Rechtshilfe - kostenpflichtig",
    "title": "",
    "phone": "0900 99 22 88",
    "email": "",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "Die ersten 19 Minuten CHF 0.08/Min, ab der 20. Minute CHF 1.90/Min."
  },
  {
    "company": "Gebäudeversicherung SO",
    "person": "Hr. Borer",
    "title": "",
    "phone": "032 627 97 33",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Sanitär Frutiger Zbinden",
    "person": "Hr. O. Moser",
    "title": "",
    "phone": "033 244 90 90 / 033 244 90 90",
    "email": "info@fzag.ch / info@fzag.ch ::: o.moser@fzag.ch",
    "website": "http://www.fzag.ch/de/ / http://www.fzag.ch/de/",
    "address": "Oberhofen\nCH",
    "labels": "Aeschlen ::: Hilterfingen ::: * myContacts",
    "notes": "Aeschlen & Hilterfingen"
  },
  {
    "company": "Mobiliar",
    "person": "Huggenberger Oliver",
    "title": "",
    "phone": "031 389 6331 / 079 308 80 18",
    "email": "oliver.huggenberger@mobi.ch",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mobiliar",
    "person": "Hummel Raphael",
    "title": "",
    "phone": "",
    "email": "raphael.hummel@mobi.ch",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Bieri Haustechnik AG",
    "person": "info@bierihaustechnikag.ch",
    "title": "",
    "phone": "",
    "email": "info@bierihaustechnikag.ch",
    "website": "https://www.bierihaustechnikag.ch/",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Grimbühler GmbH",
    "person": "",
    "title": "",
    "phone": "032 652 79 64",
    "email": "info@grimbuehler-gmbh.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": "Maler, Entsorgung und Schimmelbekämpfung"
  },
  {
    "company": "Grüter Sanitär - Geberit WC",
    "person": "",
    "title": "",
    "phone": "041 925 81 57",
    "email": "info@grueterag.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Widmer Heiztechnik AG",
    "person": "",
    "title": "",
    "phone": "034 402 55 22",
    "email": "info@heiztechnik-langnau.ch",
    "website": "https://www.heiztechnik-langnau.ch/",
    "address": "Langnau\nCH",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Helvetia",
    "person": "",
    "title": "",
    "phone": "058 280 37 11 / 058 280 30 00",
    "email": "info@helvetia.ch",
    "website": "",
    "address": "Bahnhofstrasse 42\n6210 Sursee\nCH",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "HJB Garten GmbH",
    "person": "",
    "title": "",
    "phone": "033 243 60 70",
    "email": "info@hjb-garten.ch",
    "website": "",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "ITS Kanal",
    "person": "",
    "title": "",
    "phone": "034 402 31 72",
    "email": "info@itskanal.ch / admin-zs@itskanal.ch",
    "website": "https://itskanal.ch/",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Jeker Haustechnik",
    "person": "",
    "title": "",
    "phone": "061 783 95 70",
    "email": "info@jeker-haustechnik.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: * myContacts",
    "notes": "Sanitär, Heizung"
  },
  {
    "company": "Jomos Fire Protection Solutions",
    "person": "",
    "title": "",
    "phone": "062 386 17 17",
    "email": "info@jomos.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Kaminfeger Hiltbrunner",
    "person": "",
    "title": "",
    "phone": "034 402 18 61",
    "email": "info@kaminfeger-ie.ch",
    "website": "",
    "address": "Langnau\nCH",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Liebi",
    "person": "",
    "title": "",
    "phone": "033 533 83 83",
    "email": "info@liebi.swiss",
    "website": "https://www.liebi.swiss/",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Stadler AG",
    "person": "",
    "title": "",
    "phone": "034 402 12 69",
    "email": "info@meisterhandwerk.ch",
    "website": "https://www.stadler-ag.ch/",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Messerli Bauteam",
    "person": "",
    "title": "",
    "phone": "033 222 15 44",
    "email": "info@messerli-bauteam.ch / info@messerli-bauteam.ch",
    "website": "",
    "address": "3612 Steffisburg\nCH",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Stähli Gartenbau",
    "person": "",
    "title": "",
    "phone": "034 402 61 61",
    "email": "info@staehli.ch",
    "website": "https://www.staehli.ch/",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Werder Elektro AG",
    "person": "",
    "title": "",
    "phone": "032 644 32 32",
    "email": "info@werderelektro.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Podologie Buchenhof AG",
    "person": "J. Bühler",
    "title": "",
    "phone": "041 920 16 40",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Hügli Metalexpress",
    "person": "Jacqueline und Gerhard Hügli",
    "title": "",
    "phone": "061 771 92 81",
    "email": "metallexpress@bluewin.ch",
    "website": "",
    "address": "Kundmatt 726\n4245 Kleinlützel\nCH",
    "labels": "Traube ::: * myContacts",
    "notes": "Sind auch Pächter vom Land gegenüber Kundmatt 685"
  },
  {
    "company": "Truvag AG",
    "person": "Jamie Meier",
    "title": "",
    "phone": "",
    "email": "jamie.meier@truvag.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Mobiliar",
    "person": "Jasmin Giuliano",
    "title": "",
    "phone": "",
    "email": "jasmin.giuliano@mobi.ch",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Bauknecht",
    "person": "Jasmin Vogelsang",
    "title": "Customer Relations Administration",
    "phone": "+41 062 888 33 23",
    "email": "kda_ch@europeanappliances.com",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Kaminfeger Hirschi AG",
    "person": "Jeton Ademi",
    "title": "",
    "phone": "079 301 84 36 / 031 921 72 13",
    "email": "info@kaminfegergeschaeft-Hirschi.ch",
    "website": "https://kaminfegerhirschi.ch/",
    "address": "Worblentalstrasse 33\n3063 Ittigen\nCH",
    "labels": "Aeschlen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Heizöl Kleinlützel",
    "person": "Joerin Suter AG",
    "title": "",
    "phone": "061 705 15 15",
    "email": "info@suter-joerin.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Deka - Linus Dreier AG",
    "person": "Jonas Saner",
    "title": "",
    "phone": "079 192 91 55",
    "email": "jonas.saner@dekatech.ch",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Jonny Bloch",
    "person": "Jonny Bloch",
    "title": "",
    "phone": "032 431 16 25",
    "email": "info@bloch-plattenbelaege.ch",
    "website": "https://www.bloch-plattenbelaege.ch/",
    "address": "Roggenburg\nCH",
    "labels": "Traube ::: * myContacts",
    "notes": "Kleinlützel"
  },
  {
    "company": "Möbel Schaller",
    "person": "Julia Wäsch",
    "title": "",
    "phone": "041 516 39 26",
    "email": "info@moebelschaller.ch / empfang@moebelschaller.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Service: Hr. Niederberger"
  },
  {
    "company": "Miko Immobilien",
    "person": "Julian Kaufmann",
    "title": "",
    "phone": "041 938 02 07",
    "email": "julian.kaufmann@mikoimmobilien.ch",
    "website": "",
    "address": "Hauptplatz 6\nRuswil\nSwitzerland",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Gebäudeversicherung BE",
    "person": "",
    "title": "",
    "phone": "031 925 11 11",
    "email": "kundencenter@gvb.ch",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: * myContacts",
    "notes": "Hr. Weite\nFr. Krasniqi"
  },
  {
    "company": "V-Zug",
    "person": "Kurtissi",
    "title": "",
    "phone": "058 767 30 60",
    "email": "sc_pratteln@vzug.com",
    "website": "https://www.vzug.com/",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Truvag",
    "person": "Langenstein Reto",
    "title": "",
    "phone": "",
    "email": "reto.langenstein@truvag.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Truvag",
    "person": "Läubli Marc",
    "title": "",
    "phone": "",
    "email": "marc.laeubli@truvag.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Traube 3. Stock",
    "person": "Lea Guffanti-Latscha",
    "title": "",
    "phone": "077 449 82 50",
    "email": "lea.latscha@hotmail.com / lea.latscha@hotmail.com",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "HEV Rechtsberatung Kleinlützel",
    "person": "Lorenz Altenbach",
    "title": "",
    "phone": "061 701 72 32",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Estermann - Gebäudetechnik",
    "person": "Lukas Estermann",
    "title": "",
    "phone": "041 460 30 00 / 079 453 16 42",
    "email": " l.estermann@gt-e.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Heizung - Eich\nFrau Imgrüt\n\nHandy: Hr. Estermann"
  },
  {
    "company": "Elektro Lukas GmbH",
    "person": "Lukas Koeng-Albisser",
    "title": "",
    "phone": "061 761 33 11",
    "email": "elektrolukas@gmx.ch / lukas.koeng@elektrohell.ch",
    "website": "",
    "address": "Archweg 16\n4226 Breitenbach\nCH",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": "Alte Email Adressen:\nelektrolukas@gmx.ch\nlukas.koeng@elektrohell.ch"
  },
  {
    "company": "Elektro Team Eich AG",
    "person": "Lukas Näf",
    "title": "",
    "phone": "041 460 32 32",
    "email": "lukas.naef@elektroteam-eich.ch / info@elektroteam-eich.ch",
    "website": "",
    "address": "",
    "labels": "Sempach ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Kaminfeger",
    "person": "Lukas Stirnimann",
    "title": "",
    "phone": "078 829 76 63",
    "email": "lukas@stirnimannkaminfeger.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "Feuerungskontrolleur"
  },
  {
    "company": "Lustenberger im Haushalt daheim AG",
    "person": "Lustenberger im Haushalt daheim AG",
    "title": "",
    "phone": "041 499 70 50",
    "email": "info@lustenberger.ch",
    "website": "",
    "address": "Malters\nCH",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "LUPK",
    "person": "Lydia Stirnimann",
    "title": "",
    "phone": "041 228 76 02",
    "email": "lydia.stirnimann@lukp.ch",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": "Vertretung: Fri Hellmüller"
  },
  {
    "company": "Heizmann Electro Controlling",
    "person": "Marco Heizmann",
    "title": "",
    "phone": "061 761 41 27 / 079 652 08 27",
    "email": "hecontrolling230@gmx.ch / hecontrolling230@gmx.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": "https://www.heizmann-elektrocontrolling.ch/\n"
  },
  {
    "company": "Malergeschäft Wittwer AG",
    "person": "Margrit  Tschanz",
    "title": "",
    "phone": "",
    "email": "m.tschanz@maler-wittwer.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Truvag AG",
    "person": "Mario Gander",
    "title": "",
    "phone": "041 818 77 48",
    "email": "mario.gander@truvag.ch",
    "website": "https://www.truvag.ch/home",
    "address": "Leopoldstrasse 6\n6210 Sursee\nCH",
    "labels": "* myContacts",
    "notes": "https://www.truvag.ch/datenaustausch\n"
  },
  {
    "company": "Jeker Haustechnik - Sanitär",
    "person": "Markus Palmer",
    "title": "",
    "phone": "061 551 16 33 ::: +41799167656",
    "email": "markus.palmer@jeker-haustechnik.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Schuerch-Egli",
    "person": "Martin Jäggi",
    "title": "",
    "phone": "041 462 50 06",
    "email": "m.jaeggi@schuerch-egli.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Dach-Fassade-Solar / Sempach\nKontakt PV Anlage"
  },
  {
    "company": "Elektro Schilt",
    "person": "Michael Marti",
    "title": "",
    "phone": "032 654 10 87 / 079 887 01 30",
    "email": "m.marti@schiltelektro.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Schreinerei Schwarz",
    "person": "Michael Wenger",
    "title": "",
    "phone": "032 654 24 24",
    "email": "",
    "website": "https://www.schreinereischwarz.ch/",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Kundmatt",
    "person": "Michelle Spies (Henz)",
    "title": "",
    "phone": "079 270 28 51 ::: +41792702851",
    "email": "michellehenz98@gmail.com",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Miko",
    "person": "Miko",
    "title": "",
    "phone": "",
    "email": "info@mikoimmobilien.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "POS Service Group",
    "person": "Möbel Reparatur",
    "title": "",
    "phone": "061 641 36 30",
    "email": "",
    "website": "https://pos-sg.com/de/reparatur/",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Gebrüder Estermann AG",
    "person": "Monica Galliker",
    "title": "",
    "phone": "041 458 14 27",
    "email": "info@estermanngebr.ch / monica@estermanngebr.ch",
    "website": "https://www.estermanngebr.ch/",
    "address": "Grossweid 2\n6026 Rain\nCH",
    "labels": "Sempach ::: Eich ::: * myContacts",
    "notes": "Sanitär: Hat Arbeiten in Sempach gemacht. Kann auch in  Eich arbeiten."
  },
  {
    "company": "Monika Schweikert",
    "person": "Monika Schweikert",
    "title": "",
    "phone": "079 232 46 47",
    "email": "m.schweikert@bluewin.ch",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": "Putzfrau"
  },
  {
    "company": "Mosimann Schreinerei AG",
    "person": "Mosimann Schreinerei AG",
    "title": "",
    "phone": "034 402 17 50",
    "email": "",
    "website": "",
    "address": "3550 Langnau\nCH",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Muri-Tex",
    "person": "Muri-Tex",
    "title": "",
    "phone": "041 340 50 55",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Teppich Reinigung"
  },
  {
    "company": "BTS Bautrocknungs AG",
    "person": "Nicolas Zürcher",
    "title": "Administration",
    "phone": "034 422 38 21",
    "email": "n.zuercher@bts-service.ch ",
    "website": "https://www.bts-service.ch/",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Spitex",
    "person": "Nicole Amhof",
    "title": "",
    "phone": "079 354 60 86",
    "email": "",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Mobiliar",
    "person": "Nina Schöni",
    "title": "",
    "phone": "041 926 76 57 ::: 041 926 76 76",
    "email": "nina.schoeni@mobiliar.ch",
    "website": "",
    "address": "Oberstadt 3\nSursee 6210\nCH",
    "labels": "Versicherung ::: * myContacts",
    "notes": "Sekretariat: Frau Iseli\nSchadenabteilung: Frau Schöni\nAdmin: HerrGervasio"
  },
  {
    "company": "Einwohnerkontrolle Kleinlützel",
    "person": "Noemi Wagner",
    "title": "",
    "phone": "061 775 90 02 / 061 775 90 02",
    "email": "noemi.wagner@kleinluetzel.ch / noemi.wagner@kleinluetzel.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": "Zuständig für Wasserrechnung\nStellvertretung von Fr. Wenger"
  },
  {
    "company": "Linus Dreier AG Metallwarenfabrik",
    "person": "Odette  Dreier",
    "title": "",
    "phone": "061 775 96 96 / 079 365 37 26",
    "email": "odette.dreier@dekatech.ch",
    "website": "www.dekatech.ch",
    "address": "Kleinlützel\nCH",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Jürg Kühni AG - Sanitär",
    "person": "",
    "title": "",
    "phone": "034 409 11 14",
    "email": "office@kuehniteam.ch",
    "website": "www.kuehniteam.ch",
    "address": "Langnau\nCH",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Gebäudeversicherung LU",
    "person": "Olivia Grüter",
    "title": "",
    "phone": "041 227 22 22",
    "email": "Olivia.Grueter@gvl.ch",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: * myContacts",
    "notes": ""
  },
  {
    "company": "ElektroBurri",
    "person": "Othmar Ziswiler",
    "title": "",
    "phone": "079 255 37 57",
    "email": "oz@ihr-elektropartner.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Elektroinstallationen Eich - AC"
  },
  {
    "company": "Ernährungsberaterin",
    "person": "Palladino",
    "title": "",
    "phone": "076 440 43 88",
    "email": "",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "Praxis nur am Freitag offen"
  },
  {
    "company": "Mieter Grenchen Parterre",
    "person": "Patrick Füeg",
    "title": "",
    "phone": "078 661 96 22",
    "email": "gefuege71@gmail.com",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Bürgergemeinde Grenchen - Forstbetrieb",
    "person": "Patrick Mosiman",
    "title": "Revierförster",
    "phone": "079 218 44 20",
    "email": "p.mosimann@bg-grenchen.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mobiliar",
    "person": "Patrick von Ah",
    "title": "",
    "phone": "041 926 76 32 / 079 566 50 92",
    "email": "patrick.vonah@mobi.ch",
    "website": "",
    "address": "Oberstadt 3\nSursee 6210\nCH",
    "labels": "Versicherung ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Paul Furrer AG",
    "person": "Paul Furrer AG",
    "title": "",
    "phone": "041 921 77 00",
    "email": "",
    "website": "https://www.paul-furrer.ch/home",
    "address": "Wassergrabe 2\n6210 Sursee\nCH",
    "labels": "* myContacts",
    "notes": "Rasenmäher"
  },
  {
    "company": "Traube_Studio",
    "person": "Paul Jermann",
    "title": "",
    "phone": "077 538 89 22",
    "email": "klemenspaul48@gmail.com",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": "Sa"
  },
  {
    "company": "Bendercup",
    "person": "Peter Haas",
    "title": "",
    "phone": "076 419 80 20",
    "email": "peter.haas@intergga.ch",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Grenchen_Haus",
    "person": "Petra Dellsperger",
    "title": "",
    "phone": "076 418 07 32",
    "email": "sp-momo@outlook.com / dellspergerp@gmail.com",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Pfister Gebäudersanierung",
    "person": "Pfister",
    "title": "",
    "phone": "079 218 55 33",
    "email": "info@pfister-sanierung.ch",
    "website": "https://www.pfister-sanierung.ch/",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "041 921 99 33",
    "person": "Pfister Kammerjäger",
    "title": "",
    "phone": "041 921 99 33",
    "email": "office@die-kammerjaeger.ch",
    "website": "https://www.die-kammerjaeger.ch/",
    "address": "",
    "labels": "Sempach ::: Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Sicurocentral",
    "person": "Primin Portmann",
    "title": "",
    "phone": "079 420 61 31",
    "email": "info@sicurocentral.ch / Pirmin.Portmann@sicurocentral.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "SiNa Eich"
  },
  {
    "company": "Steueramt Kanton Solothurn",
    "person": "Raffael Hauck",
    "title": "Leiter Veranlagungsbehörde",
    "phone": "061 704 70 76",
    "email": "raffael.hauck@fd.so.ch",
    "website": "",
    "address": "Amthausstrasse\n4143 Dornach\nCH",
    "labels": "Grenchen ::: Kundmatt ::: Traube ::: * myContacts",
    "notes": "Chef von Frau Müller"
  },
  {
    "company": "Mieter Grenchen_Haus",
    "person": "Remo Dellsperger",
    "title": "",
    "phone": "076 420 02 28",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "LUKB",
    "person": "Renate  Gilli",
    "title": "",
    "phone": "041 206 64 19",
    "email": "renate.gilli@lukb.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Langnau",
    "person": "Rene Heer",
    "title": "",
    "phone": "079 699 31 91",
    "email": "r.k.heer@outlook.com",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Malergeschäft Wittwer AG",
    "person": "René Hofer",
    "title": "",
    "phone": "034 402 60 00 / 079 258 32 53",
    "email": "info@maler-wittwer.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Ausgleichskasse Luzern AHV",
    "person": "Renten",
    "title": "",
    "phone": "041 209 02 04",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Helvetia",
    "person": "Reto Bannwart",
    "title": "",
    "phone": "079 253 90 12",
    "email": "reto.bannwart@helvetia.ch",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: Meinrad Privat ::: * myContacts",
    "notes": "LU 74070\nLU 45083\nAuto und Wohnmobil Versicherung"
  },
  {
    "company": "Stähli Gartenbau",
    "person": "Reto Stähli",
    "title": "",
    "phone": "079 680 02 94",
    "email": "reto@staehli.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": "Hr. Stähli wohnt in Langnau"
  },
  {
    "company": "Möbel Schaller - Dispo",
    "person": "Richard Niederberger",
    "title": "",
    "phone": "041 925 60 91",
    "email": "dispo@moebelschaller.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Sessel in Eich: Sessel von Intertime"
  },
  {
    "company": "Gebäudeversicherung BE",
    "person": "Rita Krasniqi",
    "title": "",
    "phone": "031 925 11 11",
    "email": "rkrasniqi@gvb.ch",
    "website": "https://gvb.ch/de.html",
    "address": "",
    "labels": "Versicherung ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Steueramt Kanton Solothurn",
    "person": "Roberto Stefanizzi",
    "title": "",
    "phone": "061 070 4 70 73",
    "email": "roberto.stefanizzi@fd.so.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "Veranlagung 2024"
  },
  {
    "company": "Baloise Versicherung",
    "person": "Rolf Flückiger",
    "title": "",
    "phone": "079 319 90 90 / 058 285 66 23",
    "email": "rolf.flueckiger@baloise.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Knupp Bau AG",
    "person": "Roman Lochmann",
    "title": "Bauführer",
    "phone": "041 462 71 20 / 079 6466882",
    "email": "roman.lochmann@knupp.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Bauführer: Hr. Lochmann"
  },
  {
    "company": "Seegarage Schmidli Eich",
    "person": "Roman Schmidli jr.",
    "title": "",
    "phone": "041 460 21 55",
    "email": "",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "Auto\nLU 74070\nHat 'Ersatzauto': Fr. 20/Tag\nEv. kann man die Nummer nicht mehr einlösen da Vati nicht mehr fahren darf."
  },
  {
    "company": "Stierli Sanitär",
    "person": "Ronny Stierli",
    "title": "",
    "phone": "041 921 18 91",
    "email": "info@stierlisanitaer.ch",
    "website": "https://www.stierlisanitaer.ch/",
    "address": "Sursee\nCH",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Traube 1. Stock",
    "person": "Ruth Studer (früher Bürgi)",
    "title": "",
    "phone": "077 423 86 58",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": "Hat kein Email.\nMutter von Lea Guffanti."
  },
  {
    "company": "Gemeinde Kleinlützel",
    "person": "Sabine Wenger",
    "title": "Finanzen/Steuern",
    "phone": "061 775 90 01",
    "email": "sabine.wenger@kleinluetzel.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Gebrüder Scheurer",
    "person": "Sabrina Moser",
    "title": "",
    "phone": "032 652 41 58",
    "email": "sabrina.moser@gebr-scheurer.ch",
    "website": "https://www.gebr-scheurer.ch/ / https://www.gebr-scheurer.ch/",
    "address": "Lengnau\nCH",
    "labels": "Grenchen ::: * myContacts",
    "notes": "Heizung, Sanitär und Solartechnik"
  },
  {
    "company": "Geberit",
    "person": "",
    "title": "",
    "phone": "055 221 61 11",
    "email": "sales.ch@geberit.com",
    "website": "",
    "address": "Jona\nCH",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "BaumRex",
    "person": "Samuel Bonfanti",
    "title": "",
    "phone": "078 807 44 70",
    "email": "bonfantisamuel@gmail.com",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: * myContacts",
    "notes": ""
  },
  {
    "company": "EM Electrocontrol",
    "person": "Sara Ait Baoune",
    "title": "",
    "phone": "031 980 10 64",
    "email": "sara.aitbaoune@electrocontrol.ch",
    "website": "",
    "address": "",
    "labels": "Aeschlen ::: Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Schreinerei Schwarz AG",
    "person": "Schürch",
    "title": "",
    "phone": "032 654 24 24",
    "email": "",
    "website": "",
    "address": "Grenchen\nCA",
    "labels": "Grenchen ::: * myContacts",
    "notes": "Hr. Wenger - PL Schreinerei\nHr. Zbinden - Schreiner"
  },
  {
    "company": "LUKB",
    "person": "Seline Bucher",
    "title": "",
    "phone": "041 206 62 34",
    "email": "seline.bucher@lukb.ch",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: Eich ::: * myContacts",
    "notes": "Arbeitet Mo & Do"
  },
  {
    "company": "Bauknecht",
    "person": "Service Bauknecht",
    "title": "",
    "phone": "0848 801 001",
    "email": "service@bauknecht.ch",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Meier Tobler AG",
    "person": "",
    "title": "",
    "phone": "0800 846 846",
    "email": "service.admin@meiertobler.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Elco - Service Mitte",
    "person": "",
    "title": "",
    "phone": "0848 808 808",
    "email": "Service.Mitte@ch.elco.net",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Raiffeisenbank Laufen-Thierstein",
    "person": "Silvan Ritter",
    "title": "",
    "phone": "061 766 95 53",
    "email": "silvan.ritter@raiffeisen.ch",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Schilt Elektro",
    "person": "Silvan Zurbuchen",
    "title": "",
    "phone": "032 654 1092",
    "email": "s.zurbuchen@schiltelektro.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": "Installateur\nGrenchen Elektriker"
  },
  {
    "company": "Baloise - Bank",
    "person": "Simon Jäggi",
    "title": "",
    "phone": "0848 800 806",
    "email": "simon.jaeggi@baloise.ch ",
    "website": "",
    "address": "",
    "labels": "Kundmatt ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "MBJ Bauphysik & Akkustik",
    "person": "Simon Müller",
    "title": "",
    "phone": "034 445 99 24 / 079 519 17 80",
    "email": "simon.mueller@mbj.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "4 Mitarbeiter\nArbeiten schweizweit"
  },
  {
    "company": "Prela Garage Sursee",
    "person": "Sofia",
    "title": "",
    "phone": "041 281 30 10 / 041 921 36 34",
    "email": "info@prelagarage.ch",
    "website": "",
    "address": "Allmendstrasse 10\nSursee 6210\nCH",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": "Garage - Honda Service"
  },
  {
    "company": "Spitex",
    "person": "Spitex",
    "title": "",
    "phone": "041 460 40 10",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": "- Fr. Schwegler - für Dossier von Vati verantwortlich.\n- 2. Person: Nicole Amhof\n- Villiger- Wasser\n- Rita\n-Wygartnw"
  },
  {
    "company": "Staatskanzlei Luzern - Beglaubigungsdienst",
    "person": "Staatskanzlei Luzern - Beglaubigungsdienst",
    "title": "",
    "phone": "041 228 50 24",
    "email": "",
    "website": "https://handelsregister.lu.ch/Beglaubigungen",
    "address": "Cheerstrasse 15\n6014 Luzern\nCH",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Stadtkanzlei Grenchen",
    "person": "",
    "title": "",
    "phone": "032 655 66 66",
    "email": "stadtkanzlei@grenchen.ch / finanzverwaltung@grenchen.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mobiliar",
    "person": "Stefan Lecic",
    "title": "Finanzen",
    "phone": "041 926 76 57",
    "email": "stefan.lecic@mobi.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": "Ist in Sursee"
  },
  {
    "company": "Steueramt des Kantons Solothurn - Katasterschätzung",
    "person": "Steueramt des Kantons Solothurn - Katasterschätzung",
    "title": "",
    "phone": "032 627 93 80",
    "email": "kaso@fd.so.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Steueramt des Kantons Solothurn - Veranlagungsbehörde",
    "person": "Steueramt des Kantons Solothurn - Veranlagungsbehörde",
    "title": "",
    "phone": "061 704 70 61",
    "email": "",
    "website": "",
    "address": "Amthausstrasse 15\n4143 Dornach\nCH",
    "labels": "Grenchen ::: Kundmatt ::: Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Steuerregisteramt Grenchen",
    "person": "Steuerregisteramt Grenchen",
    "title": "",
    "phone": "032 655 66 58",
    "email": "Steuerregisteramt@grenchen.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Steuerverwaltung BE",
    "person": "Steuerverwaltung BE",
    "title": "",
    "phone": "031 633 60 01",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Aeschlen ::: Hilterfingen ::: Langnau ::: * myContacts",
    "notes": "Mo, Mi, Fr: 8-13\nDi, Do: 12-16:30"
  },
  {
    "company": "Steuerverwaltung Bern - Amtlicher Wert",
    "person": "Steuerverwaltung Bern - Amtlicher Wert",
    "title": "",
    "phone": "031 633 66 44",
    "email": "",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Steuerverwaltung Langnau",
    "person": "",
    "title": "",
    "phone": "034 409 31 71",
    "email": "steuerverwaltung@langnau-ie.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Stiebel Eltron",
    "person": "Stiebel Eltron",
    "title": "",
    "phone": "0844 333 444",
    "email": "service@stiebel-eltron.ch",
    "website": "https://www.stiebel-eltron.ch/de/home.html",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Traube Einstellhalle",
    "person": "Stoffel",
    "title": "",
    "phone": "077 520 64 57",
    "email": "info@stoffel-garten.ch",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Steuern Sempach/Eich",
    "person": "Suzana Durmisi",
    "title": "Leiterin Steuern Sempach / Eich",
    "phone": "041 462 52 32",
    "email": "s.durmisi@sempach.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "SWG",
    "person": "SWG Rechnung",
    "title": "",
    "phone": "",
    "email": "noreply@swg.ch",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "SwissLife",
    "person": "SwissLife",
    "title": "",
    "phone": "",
    "email": "shareholder.services@swisslife.ch",
    "website": "",
    "address": "",
    "labels": "Meinrad Privat ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Traube 2. Stock",
    "person": "Sylvia Messerli",
    "title": "",
    "phone": "775232701",
    "email": "sam_1950@hotmail.com",
    "website": "",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "TCS",
    "person": "TCS",
    "title": "",
    "phone": "058 827 27 27",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: Meinrad Privat ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Sicce AG",
    "person": "Tellmendi",
    "title": "Trocknung",
    "phone": "061 753 83 83",
    "email": "info@sicce.ch",
    "website": "",
    "address": "Muttenz 4132\nCH",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "SWG",
    "person": "Teresa De Cesare",
    "title": "Finanz & Dienste",
    "phone": "032 654 66 01",
    "email": "",
    "website": "",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": "Grenchen"
  },
  {
    "company": "Mieter Hilterfingen_OG2",
    "person": "Teresa Tomasiewicz",
    "title": "",
    "phone": "",
    "email": "terestoma@gmail.com",
    "website": "",
    "address": "",
    "labels": "Hilterfingen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Brunner Zimmerei",
    "person": "Thomas Allemann",
    "title": "",
    "phone": "797412329",
    "email": "info@brunnerzimmerei.ch / thomas.allemann@brunnerzimmerei.ch / info@brunnerzimmerei.ch",
    "website": "https://www.brunnerzimmerei.ch/",
    "address": "",
    "labels": "Traube ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Alpha Control",
    "person": "Thomas Ast",
    "title": "",
    "phone": "079 887 01 30",
    "email": "ast@alphagmbh.swiss",
    "website": "https://alphagmbh.swiss/team/",
    "address": "",
    "labels": "Grenchen ::: * myContacts",
    "notes": ""
  },
  {
    "company": "ITS Kanal",
    "person": "Thomas Gerber",
    "title": "",
    "phone": "415628448",
    "email": "Thomas.Gerber@itskanal.ch",
    "website": "",
    "address": "",
    "labels": "Langnau ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Mieter Sempach",
    "person": "Thomas Keller",
    "title": "",
    "phone": "079 570 06 40",
    "email": "keller_thomas@bluewin.ch",
    "website": "",
    "address": "",
    "labels": "Sempach ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Stich Shreineri AG",
    "person": "Thomas Schwarz",
    "title": "AVOR Fensterfabrikation",
    "phone": "061 771 06 22",
    "email": "info@stich.ch",
    "website": "",
    "address": "Huggerwaldstrasse 227\n4245 Kleinlützel\nCH",
    "labels": "Traube ::: * myContacts",
    "notes": "Alain von Wartburg"
  },
  {
    "company": "4B",
    "person": "Tommy Schärli",
    "title": "",
    "phone": "041 914 54 81",
    "email": "tommy.schaerli@4-b.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": "Fenster Eich"
  },
  {
    "company": "TSH Dienstleistungen GmbH",
    "person": "Toni Hurni",
    "title": "",
    "phone": "079 253 08 25",
    "email": " t.hurni@tsh-dienstleistungen.ch / info@tsh-dienstleistungen.ch",
    "website": "",
    "address": "",
    "labels": "Eich ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Luzerner Staatspersonal Verband",
    "person": "Tresa Stübi-Cavegn",
    "title": "",
    "phone": "041 269 65 53",
    "email": "tresa.stuebi@lspv.ch",
    "website": "",
    "address": "",
    "labels": "Versicherung ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Runway 01",
    "person": "Urs Schneider",
    "title": "",
    "phone": "+41 (0) 79 211 16 27 / 041 534 14 15",
    "email": "urs.schneider@runway01.ch / schneider.urs@gmx.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "MartiRent",
    "person": "Ursula Marti",
    "title": "Consigliere",
    "phone": "+41 76 368 1291",
    "email": "martiursula@gmail.com",
    "website": "",
    "address": "Rte Antoine Martin 30C\nVessy 1234\nCH",
    "labels": "* myContacts",
    "notes": "Ursula Marti\nRoute Antoine-Martin 30C\nVessy 1234\n\nTel: 076 368 1291"
  },
  {
    "company": "Estermann Gebäude Technik",
    "person": "Uwe Dobroczewski",
    "title": "",
    "phone": "041 462 70 32",
    "email": "u.dobro@gt-e.ch",
    "website": "",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  },
  {
    "company": "Treppenhaus Reinigung",
    "person": "Vernuga Kanthaverl",
    "title": "",
    "phone": "078 265 04 32",
    "email": "kajaswiss@hotmail.com",
    "website": "",
    "address": "Krauerhusmatte 4\n6206 Neuenkirch\nCH",
    "labels": "Sempach ::: * myContacts",
    "notes": ""
  },
  {
    "company": "Tresor Online",
    "person": "",
    "title": "",
    "phone": "",
    "email": "",
    "website": "https://www.tresor-online.ch/Schluesseltresore-Schluesselschraenke",
    "address": "",
    "labels": "* myContacts",
    "notes": ""
  }
];
